apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-php-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-php-client
  template:
    metadata:
      labels:
        app: greeter-php-client
    spec:
      containers:
      - name: greeter-client
        image: 115100/poc-php-client-side-grpc-lb:latest
        imagePullPolicy: Always
        command:
        - "php"
        - "greeter_client.php"
