<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace GPBMetadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5010a0d677265657465722e70726f746f120967726565746572706222" .
            "1c0a0c477265657452657175657374120c0a046e616d6518012001280922" .
            "1d0a0a47726565745265706c79120f0a076d657373616765180120012809" .
            "32440a074772656574657212390a05477265657412172e67726565746572" .
            "70622e4772656574526571756573741a152e6772656574657270622e4772" .
            "6565745265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

